name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Added'
    labels:
      - 'feature'
      - 'enhancement'
      - 'add'
  - title: '🐛 Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Changed'
    labels:
      - 'chore'
      - 'change'
  - title: '🔨 Deprecated'
    labels:
      - 'deprecated'
  - title: '⚡️ Security'
    labels:
      - 'security'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
change-template: '- $TITLE'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Automatic Changelog [$RESOLVED_VERSION] - $(date +%Y-%m-%d)

  $CHANGES
  
  ## Contributors on this release
  
  $CONTRIBUTORS

draft: false # This setting ensures that a new release is not drafted.
