name: build-docker-images-workflow

on:
  pull_request:
    branches:
      - jtikekar/masterV3.0
    types: [ opened, synchronize, reopened, edited ]

  push:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'The workflow check-release was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t aasx-server-blazor-for-demo:latest -f src/docker/Dockerfile-AasxServerBlazor .

      - name: Upload image
        uses: ishworkh/container-image-artifact-upload@v1.0.0
        with:
          image: "aasx-server-blazor-for-demo:latest"
