name: Code Analysis

on:
  pull_request:
    branches:
      - main
      - release
      - 'integration/**'
    types: [opened, synchronize, reopened, edited]
  push:
    branches:
      - main
      - 'integration/**'

jobs:
  format-check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Specify the version of the .NET SDK

      - name: Install dotnet format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        run: dotnet format ./src/AasxServer.sln --verify-no-changes --verbosity detailed --report format-report.json
        env:
          PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools

      - name: Upload format report
        uses: actions/upload-artifact@v4
        with:
          name: format-report
          path: format-report.json

      - name: Check for formatting issues
        run: |
          if ($?) {
            echo "No formatting issues detected."
          } else {
            echo "Code formatting issues detected. Please fix the issues and commit again."
            exit 1
          }
